WARNING 2025-09-01 13:38:58,156 misc 2623 140010597880064 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:38:58,158 misc 2623 140010597880064 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:01,694 misc 2659 140647715434752 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:01,696 misc 2659 140647715434752 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:25,033 misc 2829 139924901191936 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:25,190 misc 2829 139924901191936 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:27,094 misc 2899 139687702225152 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:27,228 misc 2899 139687702225152 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:47,149 misc 3266 140194779578624 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:47,326 misc 3266 140194779578624 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:49,189 misc 3293 140464503746816 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:39:49,354 misc 3293 140464503746816 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:40:00,146 misc 3578 140322594664704 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:40:02,194 misc 3613 140556365029632 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:40:20,460 misc 3674 140007614320896 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:40:22,524 misc 3706 140334939889920 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:51:50,085 misc 9543 139793560649984 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 13:51:55,381 misc 9583 140031957520640 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-01 13:51:55,709 server 9583 140031957520640 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-09-01 13:51:55,709 server 9583 140031957520640 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-09-01 13:51:55,709 server 9583 140031957520640 Listening on TCP address 127.0.0.1:8000
INFO 2025-09-01 13:55:51,497 server 9583 140031957520640 Killed 0 pending application instances
WARNING 2025-09-01 13:55:59,173 misc 11461 140488741904640 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-01 13:55:59,503 server 11461 140488741904640 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-09-01 13:55:59,503 server 11461 140488741904640 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-09-01 13:55:59,503 server 11461 140488741904640 Listening on TCP address 127.0.0.1:8000
INFO 2025-09-01 13:59:50,277 server 11461 140488741904640 Killed 0 pending application instances
INFO 2025-09-01 14:00:13,009 autoreload 14362 140083638026496 Watching for file changes with StatReloader
WARNING 2025-09-01 14:00:13,136 misc 14362 140083638026496 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-01 14:00:13,430 server 14362 140083573532352 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-09-01 14:00:13,431 server 14362 140083573532352 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-09-01 14:00:13,431 server 14362 140083573532352 Listening on TCP address 127.0.0.1:8000
WARNING 2025-09-01 14:15:36,052 misc 15935 140626146074880 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-01 14:15:47,277 log 15935 140626146074880 Not Found: /dicom-viewer/api/reconstruction/types/
WARNING 2025-09-03 05:30:55,744 misc 4017 140104709771520 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-03 05:31:13,036 misc 4249 140274703999232 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
WARNING 2025-09-03 05:31:22,617 misc 4276 140111221674240 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-04 05:57:20,485 autoreload 3428 140189972537600 Watching for file changes with StatReloader
WARNING 2025-09-04 05:57:20,767 misc 3428 140189972537600 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-04 05:57:21,123 server 3428 140189908051648 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-09-04 05:57:21,123 server 3428 140189908051648 Configuring endpoint tcp:port=8000:interface=0.0.0.0
INFO 2025-09-04 05:57:21,123 server 3428 140189908051648 Listening on TCP address 0.0.0.0:8000
INFO 2025-09-04 05:57:24,351 runserver 3428 140189908051648 [32mHTTP GET / 302 [0.01, 127.0.0.1:42024][0m
INFO 2025-09-04 05:57:36,803 runserver 3428 140189908051648 [32mHTTP GET / 302 [0.00, 127.0.0.1:45854][0m
INFO 2025-09-04 05:58:05,734 autoreload 4044 140669817442560 Watching for file changes with StatReloader
WARNING 2025-09-04 05:58:05,909 misc 4044 140669817442560 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-04 05:58:06,218 server 4044 140669752956608 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-09-04 05:58:06,218 server 4044 140669752956608 Configuring endpoint tcp:port=8000:interface=0.0.0.0
INFO 2025-09-04 05:58:06,218 server 4044 140669752956608 Listening on TCP address 0.0.0.0:8000
INFO 2025-09-04 05:58:10,030 runserver 4044 140669752956608 [32mHTTP GET / 302 [0.01, 127.0.0.1:53278][0m
INFO 2025-09-04 05:58:20,032 runserver 4044 140669752956608 [32mHTTP GET / 302 [0.00, 127.0.0.1:48942][0m
ERROR 2025-09-04 05:58:27,399 log 4044 140669037311680 Invalid HTTP_HOST header: 'f7d3f2727573.ngrok-free.app'. You may need to add 'f7d3f2727573.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )(request)
    ^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'f7d3f2727573.ngrok-free.app'. You may need to add 'f7d3f2727573.ngrok-free.app' to ALLOWED_HOSTS.
WARNING 2025-09-04 05:58:27,402 runserver 4044 140669752956608 [31;1mHTTP GET / 400 [0.01, 127.0.0.1:52728][0m
INFO 2025-09-04 05:58:45,078 autoreload 4614 140601520615680 Watching for file changes with StatReloader
WARNING 2025-09-04 05:58:45,251 misc 4614 140601520615680 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-04 05:58:45,561 server 4614 140601457178304 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-09-04 05:58:45,562 server 4614 140601457178304 Configuring endpoint tcp:port=8000:interface=0.0.0.0
INFO 2025-09-04 05:58:45,562 server 4614 140601457178304 Listening on TCP address 0.0.0.0:8000
INFO 2025-09-04 05:58:49,367 runserver 4614 140601457178304 [32mHTTP GET / 302 [0.01, 127.0.0.1:44048][0m
INFO 2025-09-04 05:59:02,095 runserver 4614 140601457178304 [32mHTTP GET / 302 [0.00, 127.0.0.1:46968][0m
ERROR 2025-09-04 05:59:19,558 log 4614 140600813807296 Invalid HTTP_HOST header: 'feec14cc40cd.ngrok-free.app'. You may need to add 'feec14cc40cd.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )(request)
    ^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'feec14cc40cd.ngrok-free.app'. You may need to add 'feec14cc40cd.ngrok-free.app' to ALLOWED_HOSTS.
WARNING 2025-09-04 05:59:19,561 runserver 4614 140601457178304 [31;1mHTTP GET / 400 [0.01, 127.0.0.1:43976][0m
INFO 2025-09-04 05:59:33,397 autoreload 5097 140386372870400 Watching for file changes with StatReloader
WARNING 2025-09-04 05:59:33,574 misc 5097 140386372870400 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-04 05:59:33,880 server 5097 140386308384448 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-09-04 05:59:33,881 server 5097 140386308384448 Configuring endpoint tcp:port=8000:interface=0.0.0.0
INFO 2025-09-04 05:59:33,881 server 5097 140386308384448 Listening on TCP address 0.0.0.0:8000
ERROR 2025-09-04 05:59:45,308 log 5097 140385668032192 Invalid HTTP_HOST header: 'feec14cc40cd.ngrok-free.app'. You may need to add 'feec14cc40cd.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )(request)
    ^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'feec14cc40cd.ngrok-free.app'. You may need to add 'feec14cc40cd.ngrok-free.app' to ALLOWED_HOSTS.
WARNING 2025-09-04 05:59:45,311 runserver 5097 140386308384448 [31;1mHTTP GET / 400 [0.01, 127.0.0.1:53094][0m
ERROR 2025-09-04 05:59:46,852 log 5097 140385668032192 Invalid HTTP_HOST header: 'feec14cc40cd.ngrok-free.app'. You may need to add 'feec14cc40cd.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 132, in __acall__
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )(request)
    ^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/asgiref/sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/noctis_pro_deployment/venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'feec14cc40cd.ngrok-free.app'. You may need to add 'feec14cc40cd.ngrok-free.app' to ALLOWED_HOSTS.
WARNING 2025-09-04 05:59:46,854 runserver 5097 140386308384448 [31;1mHTTP HEAD / 400 [0.00, 127.0.0.1:53100][0m
INFO 2025-09-04 06:00:14,770 autoreload 5307 140195464786176 Watching for file changes with StatReloader
WARNING 2025-09-04 06:00:14,948 misc 5307 140195464786176 The 'pydicom.pixel_data_handlers' module will be removed in v4.0, please use 'from pydicom.pixels import apply_voi_lut' instead
INFO 2025-09-04 06:00:15,261 server 5307 140195401348800 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-09-04 06:00:15,261 server 5307 140195401348800 Configuring endpoint tcp:port=8000:interface=0.0.0.0
INFO 2025-09-04 06:00:15,262 server 5307 140195401348800 Listening on TCP address 0.0.0.0:8000
INFO 2025-09-04 06:00:24,479 runserver 5307 140195401348800 [32mHTTP GET / 302 [0.01, 127.0.0.1:34162][0m
INFO 2025-09-04 06:00:24,971 runserver 5307 140195401348800 [32mHTTP GET / 302 [0.00, 127.0.0.1:34168][0m
INFO 2025-09-04 06:00:39,507 runserver 5307 140195401348800 [32mHTTP HEAD / 302 [0.01, 127.0.0.1:45218][0m
INFO 2025-09-04 06:00:41,108 runserver 5307 140195401348800 [32mHTTP GET / 302 [0.00, 127.0.0.1:45230][0m
INFO 2025-09-04 06:00:56,763 runserver 5307 140195401348800 [mHTTP GET /login/ 200 [0.01, 127.0.0.1:38588][0m
INFO 2025-09-04 06:00:58,259 runserver 5307 140195401348800 [32mHTTP GET / 302 [0.00, 127.0.0.1:38596][0m
